//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace ForkTip.GrainInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using ForkTip.Models;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class RecipeGrainFactory
    {
        

                        public static ForkTip.GrainInterfaces.IRecipeGrain GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(ForkTip.GrainInterfaces.IRecipeGrain), 531957362, primaryKey));
                        }

                        public static ForkTip.GrainInterfaces.IRecipeGrain GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(ForkTip.GrainInterfaces.IRecipeGrain), 531957362, primaryKey, grainClassNamePrefix));
                        }

            public static ForkTip.GrainInterfaces.IRecipeGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return RecipeGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("ForkTip.GrainInterfaces.ForkTip.GrainInterfaces.IRecipeGrain")]
        internal class RecipeGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, ForkTip.GrainInterfaces.IRecipeGrain
        {
            

            public static ForkTip.GrainInterfaces.IRecipeGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (ForkTip.GrainInterfaces.IRecipeGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(ForkTip.GrainInterfaces.IRecipeGrain), (global::Orleans.Runtime.GrainReference gr) => { return new RecipeGrainReference(gr);}, grainRef, 531957362);
            }
            
            protected internal RecipeGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal RecipeGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 531957362;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "ForkTip.GrainInterfaces.ForkTip.GrainInterfaces.IRecipeGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                RecipeGrainReference input = ((RecipeGrainReference)(original));
                return ((RecipeGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                RecipeGrainReference input = ((RecipeGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return RecipeGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1097320095));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return RecipeGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<bool> ForkTip.GrainInterfaces.IRecipeGrain.TryInitialize(ForkTip.Models.Recipe value, string newPassword)
            {

                return base.InvokeMethodAsync<System.Boolean>(-884766533, new object[] {value, newPassword} );
            }
            
            System.Threading.Tasks.Task<System.Guid> ForkTip.GrainInterfaces.IRecipeGrain.Fork(string newPassword)
            {

                return base.InvokeMethodAsync<System.Guid>(1370146276, new object[] {newPassword} );
            }
            
            System.Threading.Tasks.Task ForkTip.GrainInterfaces.IRecipeGrain.SetName(string password, string value)
            {

                return base.InvokeMethodAsync<object>(2085948699, new object[] {password, value} );
            }
            
            System.Threading.Tasks.Task ForkTip.GrainInterfaces.IRecipeGrain.SetDescription(string password, string value)
            {

                return base.InvokeMethodAsync<object>(979169470, new object[] {password, value} );
            }
            
            System.Threading.Tasks.Task ForkTip.GrainInterfaces.IRecipeGrain.SetAuthor(string password, string value)
            {

                return base.InvokeMethodAsync<object>(882672596, new object[] {password, value} );
            }
            
            System.Threading.Tasks.Task ForkTip.GrainInterfaces.IRecipeGrain.SetIngredients(string password, System.Collections.Generic.List<String> value)
            {

                return base.InvokeMethodAsync<object>(-1644148259, new object[] {password, value} );
            }
            
            System.Threading.Tasks.Task ForkTip.GrainInterfaces.IRecipeGrain.SetDirections(string password, System.Collections.Generic.List<String> value)
            {

                return base.InvokeMethodAsync<object>(-614332566, new object[] {password, value} );
            }
            
            System.Threading.Tasks.Task<ForkTip.Models.Recipe> ForkTip.GrainInterfaces.IRecipeGrain.Get()
            {

                return base.InvokeMethodAsync<ForkTip.Models.Recipe>(-940922787, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("ForkTip.GrainInterfaces.ForkTip.GrainInterfaces.IRecipeGrain", 531957362)]
    internal class RecipeGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 531957362;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 531957362:  // IRecipeGrain
                        switch (methodId)
                        {
                            case -884766533: 
                                return ((IRecipeGrain)grain).TryInitialize((ForkTip.Models.Recipe)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1370146276: 
                                return ((IRecipeGrain)grain).Fork((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 2085948699: 
                                return ((IRecipeGrain)grain).SetName((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 979169470: 
                                return ((IRecipeGrain)grain).SetDescription((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 882672596: 
                                return ((IRecipeGrain)grain).SetAuthor((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1644148259: 
                                return ((IRecipeGrain)grain).SetIngredients((String)arguments[0], (System.Collections.Generic.List<String>)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -614332566: 
                                return ((IRecipeGrain)grain).SetDirections((String)arguments[0], (System.Collections.Generic.List<String>)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -940922787: 
                                return ((IRecipeGrain)grain).Get().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1097320095:  // IGrainWithGuidKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 531957362:  // IRecipeGrain
                    switch (methodId)
                    {
                        case -884766533:
                            return "TryInitialize";
                    case 1370146276:
                            return "Fork";
                    case 2085948699:
                            return "SetName";
                    case 979169470:
                            return "SetDescription";
                    case 882672596:
                            return "SetAuthor";
                    case -1644148259:
                            return "SetIngredients";
                    case -614332566:
                            return "SetDirections";
                    case -940922787:
                            return "Get";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1097320095:  // IGrainWithGuidKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
namespace ForkTip.GrainInterfacesSerializers
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using ForkTip.Models;
    using System.Collections;
    using System.Runtime.InteropServices;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class ForkTip_Models_RecipeSerialization
    {
        
        static ForkTip_Models_RecipeSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            ForkTip.Models.Recipe input = ((ForkTip.Models.Recipe)(original));
            ForkTip.Models.Recipe result = new ForkTip.Models.Recipe();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Author = input.Author;
            result.Description = input.Description;
            result.Directions = ((List<String>)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Directions)));
            result.Id = ((Guid)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Id)));
            result.Ingredients = ((List<String>)(Orleans.Serialization.SerializationManager.DeepCopyInner(input.Ingredients)));
            result.Name = input.Name;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            ForkTip.Models.Recipe input = ((ForkTip.Models.Recipe)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Author, stream, typeof(String));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Description, stream, typeof(String));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Directions, stream, typeof(List<String>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Id, stream, typeof(Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Ingredients, stream, typeof(List<String>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Name, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            ForkTip.Models.Recipe result = new ForkTip.Models.Recipe();
            result.Author = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            result.Description = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            result.Directions = ((List<String>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<String>), stream)));
            result.Id = ((Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Guid), stream)));
            result.Ingredients = ((List<String>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(List<String>), stream)));
            result.Name = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(ForkTip.Models.Recipe), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
