//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace ForkTip.Grains
{
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Orleans.CodeGeneration;
    using Orleans;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using ForkTip.Models;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("ForkTip.Grains.ProtectedGrainBase<TGrainState>")]
    public class ProtectedGrainBaseState<TGrainState> : global::Orleans.CodeGeneration.GrainState, IProtectedState<TGrainState>
    
    {
        

            public TGrainState Value { get; set; }

            public String Password { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Value", out value)) Value = (TGrainState) value;
                if (values.TryGetValue("Password", out value)) Password = (String) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("ProtectedGrainBaseState<TGrainState>( Value={0} Password={1} )", Value, Password);
            }
        
        public ProtectedGrainBaseState() : 
                base("ForkTip.Grains.ProtectedGrainBase`1")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Value"] = this.Value;
            result["Password"] = this.Password;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Value = default(TGrainState);
            this.Password = default(String);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            ProtectedGrainBaseState<TGrainState> input = ((ProtectedGrainBaseState<TGrainState>)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            ProtectedGrainBaseState<TGrainState> input = ((ProtectedGrainBaseState<TGrainState>)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            ProtectedGrainBaseState<TGrainState> result = new ProtectedGrainBaseState<TGrainState>();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("ForkTip.Grains.ForkTip.Grains.RecipeGrain")]
    public class RecipeGrainState : global::Orleans.CodeGeneration.GrainState, IProtectedState<Recipe>
    {
        

            public Recipe Value { get; set; }

            public String Password { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Value", out value)) Value = (Recipe) value;
                if (values.TryGetValue("Password", out value)) Password = (String) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("RecipeGrainState( Value={0} Password={1} )", Value, Password);
            }
        
        public RecipeGrainState() : 
                base("ForkTip.Grains.RecipeGrain")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Value"] = this.Value;
            result["Password"] = this.Password;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Value = new Recipe();
            this.Password = default(String);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            RecipeGrainState input = ((RecipeGrainState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            RecipeGrainState input = ((RecipeGrainState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            RecipeGrainState result = new RecipeGrainState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
